### ISSUE TITLE
Error in rule MakeRMA

### ISSUE THREAD

**Issue by kimnegrette3** [PacificBiosciences/pb-metagenomics-tools#5] opened 2020-10-20 19:46 UTC
Hi!
I am trying to run the Taxonomic-Functional-Profiling-Protein pipeline, but there seems to be an error during the sam2rma step. 

**This is the command I am using**:
snakemake --snakefile Snakefile-taxprot --configfile configs/Sample-Config.yaml --use-conda --cores 32

**This is the log:**
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 32
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       MakeRMA
        1       all
        2

[Tue Oct 20 12:22:59 2020]
rule MakeRMA:
    input: 3-merged/merged.ccs.merged.sam, inputs/merged.ccs.fasta
    output: 4-rma/merged.ccs.protein.readCount.rma
    log: logs/merged.ccs.MakeRMA.readCount.log
    jobid: 1
    benchmark: benchmarks/merged.ccs.MakeRMA.readCount.tsv
    wildcards: sample=merged.ccs
    threads: 24

Activating conda environment: /hpcfs/home/je.gutierrez11/pb-metagenomics/pb-metagenomics-tools-master/Taxonomic-Functional-Profiling-Protein/.snakemake/conda/0ecc3683
[Tue Oct 20 12:23:04 2020]
Error in rule MakeRMA:
    jobid: 1
    output: 4-rma/merged.ccs.protein.readCount.rma
    log: logs/merged.ccs.MakeRMA.readCount.log (check log file(s) for error message)
    conda-env: /hpcfs/home/je.gutierrez11/pb-metagenomics/pb-metagenomics-tools-master/Taxonomic-Functional-Profiling-Protein/.snakemake/conda/0ecc3683
    shell:
        /hpcfs/home/je.gutierrez11/.conda/envs/megan6/bin/sam2rma -i 3-merged/merged.ccs.merged.sam -r inputs/merged.ccs.fasta -o 4-rma/merged.ccs.protein.readCount.rma -lg -alg longReads -t 24 -mdb /hpcfs/home/je.gutierrez11/pb-metagenomics/megan-map-Jul2020-2.db -ram readCount -v 2> logs/merged.ccs.MakeRMA.readCount.log
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /hpcfs/home/je.gutierrez11/pb-metagenomics/pb-metagenomics-tools-master/Taxonomic-Functional-Profiling-Protein/.snakemake/log/2020-10-20T122250.697787.snakemake.log

And **this is the merged.ccs.MakeRMA.readCount.log**:
SAM2RMA6 - Computes a MEGAN RMA (.rma) file from a SAM (.sam) file that was created by DIAMOND or MALT                                                                                       Options:                                                                                                                                                                                     Input                                                                                                                                                                                                --in: 3-merged/merged.ccs.merged.sam                                                                                                                                                         --reads: inputs/merged.ccs.fasta                                                                                                                                                     Output                                                                                                                                                                                               --out: 4-rma/merged.ccs.protein.readCount.rma                                                                                                                                                --useCompression: true                                                                                                                                                               Reads                                                                                                                                                                                                --paired: false                                                                                                                                                                              --pairedSuffixLength: 0                                                                                                                                                              Parameters                                                                                                                                                                                           --longReads: true                                                                                                                                                                            --maxMatchesPerRead: 100                                                                                                                                                                     --classify: true                                                                                                                                                                             --minScore: 50.0                                                                                                                                                                             --maxExpected: 0.01                                                                                                                                                                          --topPercent: 10.0                                                                                                                                                                           --minSupportPercent: 0.05                                                                                                                                                                    --minSupport: 0                                                                                                                                                                              --minPercentReadCover: 0.0                                                                                                                                                                   --minPercentReferenceCover: 0.0                                                                                                                                                              --lcaAlgorithm: longReads                                                                                                                                                                    --lcaCoveragePercent: 100.0                                                                                                                                                                  --readAssignmentMode: readCount                                                                                                                                                      Classification support:                                                                                                                                                                              --parseTaxonNames: true                                                                                                                                                              Other:                                                                                                                                                                                               --firstWordIsAccession: true                                                                                                                                                                 --accessionTags: gb| ref|                                                                                                                                                                    --verbose: true                                                                                                                                                                      Version   MEGAN Community Edition (version 6.12.3, built 14 Aug 2018)                                                                                                                        Copyright (C) 2018 Daniel H. Huson. This program comes with ABSOLUTELY NO WARRANTY.                                                                                                          Caught:                                                                                                                                                                                      jloda.util.UsageException: Invalid, unknown or duplicate option: -t 24 -mdb /hpcfs/home/je.gutierrez11/pb-metagenomics/megan-map-Jul2020-2.db                                                , use option '-h' for help                                                                                                                                                                           at jloda.util.ArgsOptions.done(ArgsOptions.java:210)                                                                                                                                         at megan.tools.SAM2RMA6.run(SAM2RMA6.java:151)                                                                                                                                               at megan.tools.SAM2RMA6.main(SAM2RMA6.java:64)

the snakemake version I am using is 5.26.1

I would greatly appreciate any help or suggestion!
Thanks in advance!

**Comment by dportik** [comment] 2020-10-20 20:42
Hello,
Thank you for posting the error and the log file - this is very helpful for understanding the issue.

It seems that the `-mdb` flag isn't being recognized by MEGAN. The way MEGAN processes taxonomy information has changed over time, and the flags for using mapping files have also changed. Based on the log file, it appears that a very outdated version of MEGAN is being used (`version 6.12.3, built 14 Aug 2018`). It seems likely that this is the cause of the issue. Please download the newest release of MEGAN (and its tools), or ensure you have at least version 6.19.+. I'll make a note of the MEGAN version requirements in the documentation.

After you obtain an updated version of `sam2rma`, please let me know if your analysis finishes successfully.

**Comment by dportik** [comment] 2020-10-26 18:09
No update from OP, closing issue.

**Closed by dportik** 2020-10-26 18:09 UTC

**Comment by kimnegrette3** [comment] 2020-11-30 20:45
Hi! Sorry for the late reply! 
It worked just perfect after updating the MEGAN version. 
Thanks a lot!
