### ISSUE TITLE
File/directory is a child to another output

### ISSUE THREAD

**Issue by dgg32** [PacificBiosciences/pb-metagenomics-tools#2] opened 2020-10-08 10:55 UTC
Hi I am trying to run this workflow on my project. However, I have encountered the following error:

Building DAG of jobs...
ChildIOException:
File/directory is a child to another output:
..../661/call-export_fastq/execution/pb_binning/2-metabat-bins/661
..../661/call-export_fastq/execution/pb_binning/2-metabat-bins/661/completed.txt

My snakemake version is 5.3.0.

Thank you

**Comment by dportik** [comment] 2020-10-08 20:09
Hello,
I have issued a new release of pb-metagenomics-tools with the fix for this issue. Please download pb-metagenomics-tools v1.2.2 and let me know if you have issues with the genome-binning-pipeline. 

This issue was caused by differences from snakemake v4.8 to 5+ (the genome-binning-pipeline was originally tested with snakemake v4.8). This is similar to the issue raised [here](https://github.com/snakemake/snakemake/issues/52). The problem is that a directory and a file occurring within that directory are both are labeled as outputs for the rule. This appears to cause the conflict. 

In rule `RunMetabat` I changed the output from `2-metabat-bins/{sample}/completed.txt` to `2-metabat-bins/{sample}.completed.txt` so that it is no longer contained in the simultaneously created output directory. This eliminated the error. It was tested with snakemake v5.4.3 and v5.19.3. 

I will go ahead and close this issue. I am also closing [the other issue you posted](https://github.com/PacificBiosciences/pb-metagenomics-tools/issues/3). It was the same problem, but you ran snakemake v5.26 instead of snakemake v5.3.

**Closed by dportik** 2020-10-08 20:09 UTC
